### ISSUE TITLE
remote resource - failed connection clear selected resource

### ISSUE THREAD

**Issue by jupe** [ARMmbed/htrun#153]
if serial connection fails it clears selected resource and exclude resource releasing afterwards when calling [finish](https://github.com/ARMmbed/htrun/blob/master/mbed_host_tests/host_tests_conn_proxy/conn_primitive_remote.py#L137). PR #152 helps a bit because it verify if `selected_resource` exists before usage but doesn't fix the root cause.

See: https://github.com/ARMmbed/htrun/blob/master/mbed_host_tests/host_tests_conn_proxy/conn_primitive_remote.py#L93

**Comment by jupe** [comment]
there is already one PR which fix couple issues with remote resource (but not this one): https://github.com/ARMmbed/htrun/pull/152

**Comment by theotherjimmy** [comment]
@jupe #154 was merged, so I'm closing this issue. Please reopen if it's still present.
