### ISSUE TITLE
mbed-host-tests fails to load on mac os x

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/htrun#16]
The root cause of this problem is that python fails to return a correct fully qualified domain name for a mac on a windows LAN.

For example, a mac with a hostname of: ```bremoran-mac``` will return:
```
>>> socket.getfqdn()
'bremoran-mac'
```
```getaddrinfo()``` does not know how to parse this, which causes a gai error:
```
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```
This name does resolve correctly on our DNS, which points to an error in the implementation of ```gethostbyname``` which seems not to support aliased DNS entries.

There are few obvious solutions to this problem.
An interim solution is to use the host's internet-facing port to collect an IP address when ```getfqdn``` fails:
```Python
ipaddr = [(s.connect(('8.8.8.8', 80)), s.getsockname()[0], s.close()) for s in [socket.socket(socket.AF_INET, socket.SOCK_DGRAM)]][0][1]
```
This will not deal with machines that use multiple network interfaces, however and neither does the original solution.

I believe that the correct solution is to move the point of address resolution to a later stage in the flow.  When the mbed has reported its IP address, mbed-host-tests should run the code above with a slight modification:
```Python
ipaddr = [(s.connect((mbedIPaddr, 80)), s.getsockname()[0], s.close()) for s in [socket.socket(socket.AF_INET, socket.SOCK_DGRAM)]][0][1]
```

**Comment by rainierwolfcastle** [comment]
http://jira-dev0.cambridge.arm.com/browse/IOTSYST-190

**Comment by rainierwolfcastle** [comment]
ARM Internal Ref: IOTSYST-450

**Comment by bittailor** [comment]
I had the some problem on my mac os x machine. @bremoran's interim solution fixed it also on my machine. Thanks a lot.

**Comment by mazimkhan** [comment]
@bremoran, @bittailor I don't see this issue any more on mac m/c I have. Can you please retest with latest version and share the feedback.

**Comment by bittailor** [comment]
@mazimkhan I tried the latest version (0.1.22) on my mac an all works fine. So for me the issue is gone with the latest version.
