### ISSUE TITLE
CircleCI hasn't been passing for a while.

### ISSUE THREAD

**Issue by cmonr** [ARMmbed/htrun#196]
Reference: https://circleci.com/gh/ARMmbed/htrun

**Comment by ciarmcom** [comment]
ARM Internal Ref: MBOTRIAGE-936

**Comment by bridadan** [comment]
Agreed, time to kill it since we run everything on travis anyway. @theotherjimmy I don't have the permissions to turn off circleci. I think you need to do that on the circleci side.

**Comment by OPpuolitaival** [comment]
@theotherjimmy can you disable circleci for this repo?

**Comment by cmonr** [comment]
The CircleCI webhook have been removed.

Was kinda hoping that we would fix the issues instead.
