### ISSUE TITLE
wait us auto - more descriptive information provided

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/htrun#20]
Currently the script wait_us_auto (I figured this it the file for ticker tests for example), prints this:

```
HOST: Start test...
* in 0.99 sec (0.01) [OK]
```

And I had another platform with this output:
```
HOST: Start test...
* in 2.00 sec (1.00) [FAIL]   
```

What are  those 2 numbers? The first is the actual time it took to get a character (0.99) and the second is deviation? It helped me to look at here to get more info what is the output (https://github.com/ARMmbed/htrun/blob/master/mbed_host_tests/host_tests/wait_us_auto.py#L62).

It would help us to get more descriptive output.

**Comment by PrzemekWirkus** [comment]
Yes, first number is time measured and second in braces is a deviation from assumed 1 sec.

**Comment by PrzemekWirkus** [comment]
You are right, I will fix this. It should be more verbose!

**Comment by PrzemekWirkus** [comment]
Fixed with https://github.com/ARMmbed/htrun/commit/a5b2595336b8e821bdd04152cfd4462b00090c67

Please wait a bit for PyPI mbed-host-tests update :)

**Comment by 0xc0170** [comment]
Thanks!
