### ISSUE TITLE
htrun fails with mbedgt: cannot import name MbedBoard

### ISSUE THREAD

**Issue by studavekar** [ARMmbed/htrun#222]
steps to reproduce 

- create a fresh virtualenv 
- install htrun ` pip install mbed-host-tests`

run `mbedgt`
```
(test_htrun_gt_update) ➜  mbed-os mbedgt --help
mbedgt: Not all required Python modules were imported!
mbedgt: cannot import name MbedBoard
mbedgt: Check if:
        1. You've correctly installed dependency module using setup tools or pip:
                * python setup.py install
                * pip install <module-name>
        2. There are no errors preventing import in dependency modules
        See: https://github.com/ARMmbed/greentea#installing-greentea
```

This **effectivley breaks CI system** which would create a virtualenv and install packages using pip.

The root cause looks like latest release of [pyOCD](https://github.com/mbedmicro/pyOCD/releases/tag/v0.13.0b1)  with connector class ``` New ConnectHelper class with static methods previously in MbedBoard.```

one quick fix for compatibility is to stick to pyOCD <= 0.12.0

**Comment by SenRamakri** [comment]
Adding @theotherjimmy and @bridadan

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-44*

**Comment by studavekar** [comment]
closing it as fixed is been merged.
