### ISSUE TITLE
Support pyOCD >= 0.13.0

### ISSUE THREAD

**Issue by kjbracey-arm** [ARMmbed/htrun#231]
#223 forced htrun to use an old pyOCD.

Users are starting to shift to using pyOCD 0.13.x to pick up various thread/context handling improvements I'm working on - having to downgrade to run htrun is annoying.

CC @flit in case he has any tips for dealing with the name change. Is there any problem with requiring >=0.13.0?

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-246*

**Comment by bridadan** [comment]
The only dependency on pyocd is in the pycod plugin (which isn't used by default). So if we can verify that plugin works just fine with 0.13.x then we can definitely update the version.

**Comment by bridadan** [comment]
This was implemented in #233
