### ISSUE TITLE
Why are versions later than 1.4.1 not on pip?

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/htrun#239]

**Comment by bridadan** [comment]
They're there: https://pypi.org/project/mbed-host-tests/#history

Are you having issues installing them? Perhaps your pip installation is using its cache? You can always temporarily disable it by running `pip install --no-cache-dir mbed-host-tests`.

Also as an fyi, this project has moved to https://github.com/ARMmbed/mbed-os-tools, so please open any other issues there in the future, thanks!

**Comment by LiyouZhou** [comment]
Thank you.
