### ISSUE TITLE
Typo: handle_send_bread_cmd

### ISSUE THREAD

**Issue by salkinium** [ARMmbed/htrun#27]
Anecdotal evidence suggests that the boards don't like it when you send them :bread:.
Have you tried sending :pizza: or :hamburger: instead?

https://github.com/ARMmbed/htrun/blob/master/mbed_host_tests/__init__.py#L145

**Comment by PrzemekWirkus** [comment]
Fixed here: https://github.com/ARMmbed/htrun/commit/415ba49e4f3a81243085a537ae837bde0b8301d5. 

PS: You are welcome to send directly PR with fix for this trivia issues! :)
