### ISSUE TITLE
Switch -e (enumerate host tests) doesn't supoprt 'yotta test'

### ISSUE THREAD

**Issue by PrzemekWirkus** [ARMmbed/htrun#33]
Currently ```yotta test``` command executes in module subdirectory and ```mbedgt``` (greentea) can't deduce and enumerate host tests in default ```module/test/host_tests```.

How to reproduce:
```
$ cd C:\Work\mbed-drivers
$ yotta test
```
* ```yotat test``` execution directory of tests (mbedgt): ```c:\Work\mbed-drivers\build\frdm-k64f-gcc\test```
  * Default host test directory assumed by greentea: ```c:\Work\mbed-drivers\build\frdm-k64f-gcc\test\test\host_tests```
  * Should be: ```c:\Work\mbed-drivers\build\test\host_tests```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSYST-588

**Comment by niklas-arm** [comment]
I can reproduce this issue with v0.1.18.

**Comment by niklas-arm** [comment]
Note that this can be fixed by appending this to the `module.json`:

```json
  "scripts": {
    "testReporter": [
      "mbedgt",
      "--digest",
      "stdin",
      "-v",
      "-V",
      "-e", "test/host_tests"
    ]
  }
```

**Comment by PrzemekWirkus** [comment]
Obsolete issue. Closing.
