### ISSUE TITLE
What is a Rump Up?

### ISSUE THREAD

**Issue by niklas-arm** [ARMmbed/htrun#41]
https://github.com/ARMmbed/htrun/blob/master/mbed_host_tests/host_tests/base_host_test.py#L25

**Comment by 0xc0170** [comment]
Is this a proper naming for those 2 functions - rampUp, rampDown? 

We have setup and teardown in other tools.

**Comment by niklas-arm** [comment]
:+1:  for setup and teardown, as they are more closely associated with testing.
RampUp and RampDown seems to be a business or engineering term, not usually associated with testing.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSYST-693

**Comment by marhil01** [comment]
We have to check the naming in clitest if other our tools will have setup and teardown

**Comment by niklas-arm** [comment]
There seems to be massive confusion in our python scripts:

- [Plenty of Ramps](https://github.com/search?utf8=✓&q=user%3Aarmmbed+language%3Apython+rampdown&type=Code).
- [Plenty of Teardowns](https://github.com/search?utf8=✓&q=user%3Aarmmbed+language%3Apython+teardown&type=Code).
- [I could not find any rampups or rampdowns in C or C++ code](https://github.com/search?utf8=✓&q=user%3Aarmmbed+language%3Ac+ramp&type=Code).
- [This is not surprising as "setup" and "teardown" are the **defacto standard terms** for testing](https://github.com/search?utf8=✓&q=user%3Aarmmbed+language%3Ac+teardown&type=Code).

cc @hugovincent @bogdanm

**Comment by marhil01** [comment]
ok there will be added setUp and tearDown to clitest framework: IOTSYST-695
