### ISSUE TITLE
Rename rampUp/Down to setup/teardown

### ISSUE THREAD

**Issue by niklas-arm** [ARMmbed/htrun#48]
See https://github.com/ARMmbed/htrun/issues/41#issuecomment-165783839
and also https://github.com/ARMmbed/mbed-clitest/pull/207.

**Comment by 0xc0170** [comment]
+1 to have unified naming for these functions

**Comment by PrzemekWirkus** [comment]
@stegut01 Please implement this simple issue! :)

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSYST-740

**Comment by PrzemekWirkus** [comment]
We've merged this change already. We will release soon so you will be able to change your pending PRs using setup/teardown.

BTW, we still didn't make setup->test->teardown robust so it might not work as expected.

**Comment by PrzemekWirkus** [comment]
I will close this because issue is about renaming not actually making teardown() work.
