### ISSUE TITLE
Serial communication introduces second long delays

### ISSUE THREAD

**Issue by geky** [ARMmbed/htrun#96]
Most noticable on echo tests. Causes the [echo tests](https://github.com/ARMmbed/mbed-os/blob/master/TESTS/mbed_drivers/echo/main.cpp) to fail without a timeout of >2 minutes.

cc @PrzemekWirkus @bridadan

**Comment by geky** [comment]
I made a workaround #97. There is probably a better way to solve it, but this could work as a temporary solution.

**Comment by PrzemekWirkus** [comment]
@geky How did you test it?

**Comment by PrzemekWirkus** [comment]
OK, I had a chance to check it. It looks promising, gonna release this to PyPI :)

**Comment by geky** [comment]
Ah tested locally with mbedgt and the tests in mbedmicro/mbed. Glad it worked for you : )
